#!/bin/bash

# This script takes a single command line argument
# and searches the command history for entries that match the argument.

# The first command line argument is accessed with $1
search_term=$1
echo $search_term
# The history command is used to display the command history
# The output is then piped to the grep command
# which searches for lines that contain the search term
history | grep $search_term
