#!/bin/bash
# github.com/richkmls
# Quickly find a previous command that you executed in the bash shell
#
# This script searches the bash history file for a given term
# Usage: ./search_history.sh [term]
# If no term is provided, the script will prompt the user for input

# Check if the user has provided a command line argument
if [ -z "$1" ]; then
  # If not, prompt the user for a search term
  echo -n "Please enter a search term: "
  read search_term
else
  # If yes, assign it to the search_term variable
  search_term=$1
fi

# Set the history file path
HISTFILE=~/.bash_history

# Read the history file
history -r

# Search the history file for the search term
history | grep $search_term
